# Generated by Django 4.1.3 on 2022-11-18 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('menu', models.IntegerField()),
                ('likes', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
            ],
        ),
    ]
