# Generated by Django 4.1.3 on 2022-11-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_vote_time',
        ),
        migrations.AddField(
            model_name='employee',
            name='last_vote_time',
            field=models.DateField(null=True),
        ),
    ]
